//
//  ClipboardManager.swift
//  boringNotch
//
//  Polls NSPasteboard for new copies. Skips concealed/transient items (password
//  managers), guards against re-capturing our own writes, dedupes the newest
//  entry, and caps history to `clipboardHistoryLimit`. Text/links persist;
//  images are session-only.
//

import AppKit
import Combine
import Defaults

@MainActor
final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var items: [ClipboardItem] = []

    private let store = CodableFileStore<ClipboardItem>(subdirectory: "Clipboard", filename: "clipboard.json")
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    /// changeCount of our own `copyToPasteboard` write, so polling ignores it.
    private var ignoreChangeCount: Int = -1
    private var enableCancellable: AnyCancellable?

    // Pasteboard types that mark transient/secret content we must not record.
    private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private init() {
        lastChangeCount = NSPasteboard.general.changeCount
        items = store.load()
        enableCancellable = Defaults.publisher(.enableClipboard)
            .sink { [weak self] change in
                Task { @MainActor in
                    change.newValue ? self?.start() : self?.stop()
                }
            }
    }

    func start() {
        guard Defaults[.enableClipboard], timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let t = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        // Ignore the change produced by our own copy-back.
        if changeCount == ignoreChangeCount { return }

        let types = Set(pasteboard.types ?? [])
        if !types.isDisjoint(with: Self.skipTypes) { return }

        capture()
    }

    private func capture() {
        // Prefer text/link; fall back to an image.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind: ClipboardKind = isLink(string) ? .link : .text
            record(ClipboardItem(kind: kind, text: string))
            return
        }
        if let objects = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = objects.first {
            record(ClipboardItem(kind: .image, image: image))
        }
    }

    private func record(_ item: ClipboardItem) {
        // Dedupe a consecutive duplicate of the newest text/link entry.
        if let first = items.first, first.kind == item.kind, first.text == item.text, item.kind != .image {
            return
        }
        items.insert(item, at: 0)
        let limit = max(1, Defaults[.clipboardHistoryLimit])
        if items.count > limit { items = Array(items.prefix(limit)) }
        persist()
    }

    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link:
            if let text = item.text { pasteboard.setString(text, forType: .string) }
        case .image:
            if let image = item.image { pasteboard.writeObjects([image]) }
        }
        // Record so the next poll skips re-capturing our own write.
        ignoreChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        persist()
    }

    func clearAll() {
        items.removeAll()
        persist()
    }

    private func isLink(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(" "), let url = URL(string: trimmed), let scheme = url.scheme else { return false }
        return scheme == "http" || scheme == "https"
    }

    private func persist() {
        store.save(items.filter(\.isPersistable))
    }
}
